// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChzQmEjlD-S_F7SPDOWL0MlQLNKD1-tvk',
    appId: '1:836355816283:web:81fa163a8714362d7a387e',
    messagingSenderId: '836355816283',
    projectId: 'smartpayy',
    authDomain: 'smartpayy.firebaseapp.com',
    storageBucket: 'smartpayy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8mYDA4NQJbANwAXZibrccFpWBnCAZw0I',
    appId: '1:836355816283:android:1d47732a214a06537a387e',
    messagingSenderId: '836355816283',
    projectId: 'smartpayy',
    storageBucket: 'smartpayy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAosjJJi98lYIO8ltDA5qlrIpTgbiFStHA',
    appId: '1:836355816283:ios:d98144f5fbc08c4c7a387e',
    messagingSenderId: '836355816283',
    projectId: 'smartpayy',
    storageBucket: 'smartpayy.appspot.com',
    iosClientId: '836355816283-a99ln968vrr5a7777bic04hg0e929k6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.rolandSalaryWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAosjJJi98lYIO8ltDA5qlrIpTgbiFStHA',
    appId: '1:836355816283:ios:d98144f5fbc08c4c7a387e',
    messagingSenderId: '836355816283',
    projectId: 'smartpayy',
    storageBucket: 'smartpayy.appspot.com',
    iosClientId: '836355816283-a99ln968vrr5a7777bic04hg0e929k6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.rolandSalaryWebsite',
  );
}
